### ISSUE TITLE
EventSauce 3.x support

### ISSUE THREAD

**Issue by PonendoPonens** [eventsauce-symfony/eventsauce-messenger#1]
I'm using this package (not whole bundle). Composer breaks with ^2.0 requirement of EventSauce package.
MessegeSubscriberInterface is deprecated. Any chances for update?

**Comment by andrzepakula** [comment]
Yes in the coming days.

**Comment by PonendoPonens** [comment]
Thats great! Thanks

**Comment by andrzepakula** [comment]
Done. Many changes has been released with version 3.0, check doc
